(function(){
'use strict';
const DATA_URL='https://script.google.com/macros/s/AKfycbwgn9wMf-aMhkL_9ONO7AFPpOhDqj2ZMHzDHPgpYnzTqcqlTYToxxDCKL1R-tlMdVgU/exec';
let DATA=null,charts={},trendMetric='avg_rate',trendPeriod=12,changeFilter='all';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pct=v=>v==null?'—':(v*100).toFixed(1)+'%';
const pp=v=>v==null?'—':(v>=0?'+':'')+(v*100).toFixed(1)+'%p';
const capa=v=>v==null?'—':(v/10000).toLocaleString('ko-KR',{maximumFractionDigits:1})+'만톤';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const cls=v=>v>.0005?'up':v<-.0005?'down':'flat';
function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function baseChartOpts(yFmt){return {responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{backgroundColor:'#07111f',titleColor:'#fff',bodyColor:'#dbe7f5',padding:10,displayColors:false,callbacks:{label:c=>c.dataset.label+': '+(c.dataset._fmt?c.dataset._fmt(c.raw):c.raw)}}},scales:{x:{grid:{display:false},ticks:{color:css('--muted'),font:{size:10},maxRotation:0,autoSkip:true,maxTicksLimit:8}},y:{grid:{color:css('--line')},ticks:{color:css('--muted'),font:{size:10},callback:yFmt}}}}}
function lineChart(id,labels,values,label,fmt,color,min,max){destroy(id);let opt=baseChartOpts(v=>fmt(v));if(min!=null)opt.scales.y.min=min;if(max!=null)opt.scales.y.max=max;let ds={label,data:values,borderColor:color,backgroundColor:color,pointRadius:values.length>20?0:2.5,pointHoverRadius:4,tension:.28,fill:true};ds._fmt=fmt;ds.backgroundColor=color+'18';charts[id]=new Chart($(id),{type:'line',data:{labels,datasets:[ds]},options:opt})}
function barChart(id,labels,values,label,fmt,color,horizontal=false){destroy(id);let opt=baseChartOpts(v=>fmt(v));if(horizontal){opt.indexAxis='y';opt.scales.y.grid.display=false;delete opt.scales.y.ticks.callback;opt.scales.y.ticks.autoSkip=false;opt.scales.y.ticks.font={size:9};opt.scales.x.grid.color=css('--line');opt.scales.x.ticks.callback=v=>fmt(v)}let ds={label,data:values,backgroundColor:color,borderRadius:6};ds._fmt=fmt;charts[id]=new Chart($(id),{type:'bar',data:{labels,datasets:[ds]},options:opt})}
function activateTab(id){$$('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));setTimeout(()=>Object.values(charts).forEach(c=>c.resize()),20)}
$$('.tab-btn').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab));
$('#refresh').onclick=()=>location.reload();
$('#theme').onclick=()=>{let t=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',t);try{localStorage.setItem('sm-dash-theme',t)}catch(e){};renderOverview();renderCharts()};
function renderMeta(){let m=(DATA.generated_at?'마지막 갱신 '+new Date(DATA.generated_at).toLocaleString('ko-KR'):'실시간 DB')+'<br>'+DATA.facility_count+'개 설비 · '+DATA.regions.length+'개 지역';$('#latest').textContent='Latest '+DATA.w_cur;['overview','trend','regions','changes'].forEach(x=>$('#'+x+'-meta').innerHTML=m)}
function renderKpis(){let n=DATA.national,cur=n.at(-1),prev=n.at(-2)||cur,rd=cur.avg_rate-prev.avg_rate,cd=cur.online_capa-prev.online_capa,rc=DATA.changes.filter(x=>x.rate_changed).length;let rows=[['National operating rate',pct(cur.avg_rate),pp(rd),'전주 '+pct(prev.avg_rate),cls(rd)],['Operating capacity',capa(cur.online_capa),(cd>=0?'+':'')+capa(cd),'전주 '+capa(prev.online_capa),cls(cd)],['Installed capacity',capa(DATA.total_capa_latest),DATA.facility_count+'개 설비',DATA.regions.length+'개 지역','flat'],['Weekly movers',DATA.changes.length+'개','가동률 '+rc+'개','상태만 '+(DATA.changes.length-rc)+'개','flat']];$('#kpis').innerHTML=rows.map(r=>`<div class="card kpi"><div class="kpi-label">${r[0]}</div><div class="kpi-value tabnums">${r[1]}</div><div class="kpi-foot"><span class="${r[4]}">${r[2]}</span><span>${r[3]}</span></div></div>`).join('')}
function renderOverview(){let n=DATA.national.slice(-12),v=n.map(x=>x.avg_rate),avg=v.reduce((a,b)=>a+b,0)/v.length;$('#mini').innerHTML=[['현재',pct(v.at(-1))],['12W 평균',pct(avg)],['12W 최고',pct(Math.max(...v))],['12W 최저',pct(Math.min(...v))]].map(x=>`<div class="mini-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');let sm=DATA.status_mix,total=Object.values(sm).reduce((a,b)=>a+b,0),defs=[['good','정상 가동','--green'],['warning','저부하·감산','--amber'],['serious','정기보수','--orange'],['critical','가동 중단','--red']],start=0,parts=[];defs.forEach(d=>{let share=(sm[d[0]]||0)/total*100;parts.push(`${css(d[2])} ${start}% ${start+share}%`);start+=share});$('#ring').style.background=`conic-gradient(${parts.join(',')})`;$('#ring-total').textContent=capa(total);$('#status-list').innerHTML=defs.map(d=>{let val=sm[d[0]]||0;return `<div class="status-row"><span class="dot" style="background:${css(d[2])}"></span><span>${d[1]} <small>${capa(val)}</small></span><b>${pct(val/total)}</b></div>`}).join('');$('#regions-quick').innerHTML=DATA.regions.slice(0,8).map(r=>`<div class="region-row"><div class="region-name">${esc(r.region)}</div><div class="track"><div class="fill" style="width:${Math.max(1,r.rate*100)}%"></div></div><div class="region-val">${pct(r.rate)}</div></div>`).join('');$('#changes-quick').innerHTML=DATA.changes.slice(0,7).map(c=>{let d=(c.rate_cur??0)-(c.rate_prev??0);return `<div class="change-item"><div><div class="change-name">${esc(c.company)}</div><div class="change-meta">${esc(c.region)} · ${capa(c.capa)}</div><div class="change-status">${esc(c.status_prev)} → ${esc(c.status_cur)}</div></div><div class="change-value ${cls(d)}">${pct(c.rate_prev)} → ${pct(c.rate_cur)}</div></div>`}).join('')}
function renderTrendStats(){let rows=[...DATA.national];if(trendPeriod!=='all')rows=rows.slice(-Number(trendPeriod));let m={avg_rate:['National operating rate','캐파 가중 평균',pct,0,1],online_capa:['Operating capacity','실제 가동 Capa',capa,0,null],total_capa:['Installed capacity','총 설비 Capa',capa,0,null]}[trendMetric],vals=rows.map(r=>r[trendMetric]),last=vals.at(-1),prev=vals.at(-2)??last,avg=vals.reduce((a,b)=>a+b,0)/vals.length;$('#trend-title').textContent=m[0];$('#trend-sub').textContent=m[1];$('#trend-stats').innerHTML=[['현재',m[2](last)],['기간 평균',m[2](avg)],['기간 최고',m[2](Math.max(...vals))],['전주 변화',trendMetric==='avg_rate'?pp(last-prev):(last-prev>=0?'+':'')+capa(last-prev)]].map(x=>`<div class="mini-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function renderRegions(){let regs=DATA.regions.map(r=>({...r,online:r.capa*r.rate})),hi=[...regs].sort((a,b)=>b.rate-a.rate)[0],lo=[...regs].sort((a,b)=>a.rate-b.rate)[0],big=[...regs].sort((a,b)=>b.capa-a.capa)[0];$('#region-summary').innerHTML=[['Highest operating rate',hi.region,pct(hi.rate)],['Largest capacity',big.region,capa(big.capa)],['Lowest operating rate',lo.region,pct(lo.rate)]].map(x=>`<div class="card kpi"><div class="kpi-label">${x[0]}</div><div class="kpi-value" style="font-size:19px">${esc(x[1])}</div><div class="kpi-foot"><span class="flat">${x[2]}</span></div></div>`).join('');renderRegionTable()}
function renderRegionTable(){let sort=$('#region-sort').value,regs=DATA.regions.map(r=>({...r,online:r.capa*r.rate})).sort((a,b)=>b[sort]-a[sort]);$('#region-body').innerHTML=regs.map((r,i)=>`<tr><td><span class="rank">${i+1}</span>${esc(r.region)}</td><td>${r.count}</td><td>${capa(r.capa)}</td><td><span class="chip">${pct(r.rate)}</span></td><td>${capa(r.online)}</td></tr>`).join('')}
$('#region-sort').onchange=renderRegionTable;
function match(c,f){if(f==='all')return true;if(f==='rate')return c.rate_changed;if(f==='status')return !c.rate_changed;if(f==='restart')return (c.rate_prev===0&&c.rate_cur>0)||/재가동|생산 개시|증산/.test(c.status_cur||'');if(f==='shutdown')return c.rate_cur===0||/보수|중단|정지|정비/.test(c.status_cur||'');return true}
function renderChanges(){let arr=DATA.changes.filter(c=>match(c,changeFilter));$('#filter-sub').textContent=`총 ${DATA.facility_count}개 설비 중 ${arr.length}개 표시`;$('#change-grid').innerHTML=arr.length?arr.map(c=>{let d=(c.rate_cur??0)-(c.rate_prev??0);return `<article class="card change-card"><div class="change-card-head"><div><div class="change-card-name">${esc(c.company)}</div><div class="change-meta">${esc(c.region)} · ${capa(c.capa)}</div></div><span class="badge ${c.rate_changed?'rate':''}">${c.rate_changed?'가동률 변경':'상태 변경'}</span></div><div class="change-card-rate ${cls(d)}">${pct(c.rate_prev)} → ${pct(c.rate_cur)} ${c.rate_changed?`<span style="font-size:10px">${pp(d)}</span>`:''}</div><div class="change-card-status">${esc(c.status_prev)}${c.status_prev!==c.status_cur?' → '+esc(c.status_cur):''}</div></article>`}).join(''):'<div class="empty" style="grid-column:1/-1">조건에 해당하는 설비가 없습니다.</div>'}
$$('#change-filter .seg').forEach(b=>b.onclick=()=>{$$('#change-filter .seg').forEach(x=>x.classList.remove('active'));b.classList.add('active');changeFilter=b.dataset.filter;renderChanges()});
$$('#metric .seg').forEach(b=>b.onclick=()=>{$$('#metric .seg').forEach(x=>x.classList.remove('active'));b.classList.add('active');trendMetric=b.dataset.metric;renderTrendStats();renderCharts()});
$$('#period .seg').forEach(b=>b.onclick=()=>{$$('#period .seg').forEach(x=>x.classList.remove('active'));b.classList.add('active');trendPeriod=b.dataset.period;renderTrendStats();renderCharts()});
function renderCharts(){if(!DATA)return;let n=DATA.national.slice(-12);lineChart('#overview-chart',n.map(x=>x.week),n.map(x=>x.avg_rate),'가동률',pct,css('--brand'),0,1);let rows=[...DATA.national];if(trendPeriod!=='all')rows=rows.slice(-Number(trendPeriod));let fmt=trendMetric==='avg_rate'?pct:capa,max=trendMetric==='avg_rate'?1:null;lineChart('#trend-chart',rows.map(x=>x.week),rows.map(x=>x[trendMetric]),$('#trend-title').textContent,fmt,css('--brand'),0,max);lineChart('#capacity-chart',n.map(x=>x.week),n.map(x=>x.online_capa),'가동 Capa',capa,css('--cyan'),0,null);let d=n.map((x,i)=>i?x.avg_rate-n[i-1].avg_rate:0);barChart('#delta-chart',n.map(x=>x.week),d,'주간 변화',pp,css('--brand'));let regs=DATA.regions.map(r=>({...r,online:r.capa*r.rate}));let rr=[...regs].sort((a,b)=>b.rate-a.rate);barChart('#region-rate-chart',rr.map(x=>x.region),rr.map(x=>x.rate),'가동률',pct,css('--brand'),true);let rc=[...regs].sort((a,b)=>b.capa-a.capa);barChart('#region-capa-chart',rc.map(x=>x.region),rc.map(x=>x.online),'가동 Capa',capa,css('--cyan'),true)}
function renderAll(){renderMeta();renderKpis();renderOverview();renderTrendStats();renderRegions();renderChanges();renderCharts();$('#loading').style.display='none'}
fetch(DATA_URL+'?_='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);DATA=d;renderAll()}).catch(e=>{$('#loading').style.display='none';let b=$('#banner');b.textContent='데이터 연결 실패: '+e.message;b.classList.add('show')});
})();
